name: Windows Cloud PC (เปิดเสียง)

on:
  workflow_dispatch: # เริ่มการทำงานด้วยตนเอง

jobs:
  build:
    runs-on: windows-latest # รันบน Windows ล่าสุด
    timeout-minutes: 9999 # กำหนดเวลาสูงสุด (ปรับได้ตามต้องการ)

    steps:
      - name: ดาวน์โหลดไฟล์ที่จำเป็น
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/nlx5eom9f00k9d9hy5pvx/Downloads.bat?rlkey=wyivysvz7qhw4ewbywo4mm1d0&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: ตั้งค่าและเริ่ม ngrok ด้วยที่อยู่ที่สงวนไว้
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} # โทเค็น ngrok ของคุณ (เก็บเป็นความลับ)
          NGROK_REGION: ap # เลือกภูมิภาคที่ใกล้คุณที่สุด
        run: |
          ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
          ngrok tcp --region $Env:NGROK_REGION 5900 &  # เริ่ม ngrok ในพื้นหลัง
          $ngrokUrl = (ngrok api tunnel-sessions list | ConvertFrom-Json)[0].public_url
          echo "NGROK_URL=$ngrokUrl" >> $env:GITHUB_ENV # เก็บ URL ที่คงที่

      - name: เปิดการเข้าถึง RDP
        run: cmd /c Access.bat       

      - name: เข้าสู่ระบบ Remote Desktop Protocol
        run: cmd /c startaudio.bat

      - name: นับเวลา
        run: cmd /c loop.bat

      - name: แสดง URL ของ Ngrok
        run: echo "URL ngrok ที่ใช้งานได้ตลอดคือ: ${{ env.NGROK_URL }}" # เข้าถึง URL ได้จากทุกขั้นตอน
